##
# compose-core.yml
#
# Files in this direcotry named compose-*.yml rely on inheriting from the 
# services defined here.
# 
# Usage:
#   docker-compose -f compose-core.yml
##

version: "3"
services:

  web:
    build: ./web
    image: anyforecast/web
    container_name: anyforecast-web
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - DB_URL=${DB_URL}
      - WEB_PORT=${WEB_PORT}

  minio:
    build: ./minio
    image: anyforecast/minio
    container_name: anyforecast-minio
    volumes:
      - minio_data:/data
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
    
  mlflow:
    build: ./mlflow
    image: anyforecast/mlflow
    container_name: anyforecast-mlflow
    environment:
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      - BACKEND_URI=${BACKEND_URI}
      - ARTIFACT_ROOT=${ARTIFACT_ROOT}
    ports:
      - ${MLFLOW_PORT}:${MLFLOW_PORT}
    depends_on:
      - postgres
      - minio

  postgres:
    build: ./postgres
    image: anyforecast/postgres
    container_name: anyforecast-postgres
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  minio_data:
  
  
